
name: Mirror to Based-Agents-Factory
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: 'https://x-access-token:${{ secrets.MIRROR_PUSH_TOKEN }}@github.com/Based-Agents-Factory/Agent-DentConnect-70bc08e5.git'
          ssh_private_key: ''
